project:
  type: website

website:
  title: "Netlify deployment test site"
  site-url: "https://sellorm-qweb.netlify.app"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: flatly
    css: styles.css
    toc: true



